POST http://localhost:3003/user/create
Content-Type: application/json

{
    "name":"Pompom",
    "email": "pompom@pompom.pom",
    "password": "mipomps"
}

###
POST http://localhost:3003/post/create
Content-Type: application/json

{
    "photo":"Foto de passarinho",
    "description": "Passarinhos voando na paisagem",
    "type": "normal",
    "createdAt": "2023-01-30",
    "authorId": "e2ad7786-6fcd-4c95-89ba-ed4f06aa986e"
}

###
GET http://localhost:3003/post/getId/b1bfe3c7-137c-415a-b880-2e3439f92c20
Content-Type: application/json

###
POST http://localhost:3003/user/makeFriendship
Content-Type: application/json

{
    "idUser":"53b4c0c7-7883-430b-88d6-9a2bcaf32ae0",
    "idFriend":"e2ad7786-6fcd-4c95-89ba-ed4f06aa986e"
}