POST http://localhost:3003/user/create
Content-Type: application/json

{
    "name":"Jess",
    "email": "jess@jess.com",
    "password": "56784344"
}

###
POST http://localhost:3003/post/create
Content-Type: application/json

{
    "photo":"Foto de passarinho",
    "description": "Passarinhos voando na paisagem",
    "type": "normal",
    "createdAt": "2023-01-30",
    "authorId": "e2ad7786-6fcd-4c95-89ba-ed4f06aa986e"
}

###
GET http://localhost:3003/post/getId/b1bfe3c7-137c-415a-b880-2e3439f92c20
Content-Type: application/json
